version: '3.7'
services: 
    backend:
        container_name: backend
        build: 
            context: ./backend/
            dockerfile: Dockerfile
        ports: 
            - "8000:8000"
        restart: always
    frontend:
        depends_on: 
            - backend
        container_name: frontend
        build: 
            context: ./frontend/
            dockerfile: Dockerfile
        ports: 
            - "5000:5000"
        restart: always
